window.i18n = {
  en: {
    site: { title: 'VTPlayer — Sharper. Smoother. Better.' },
    hero: { heading: 'VTPlayer', tagline: 'Sharper. Smoother. Better.' },
    quicknav: { page: 'Page', links: 'Links', more: 'More', overview: 'Overview', demo: 'Demo', features: 'Features', install: 'Install', github: 'GitHub', releases: 'Releases', raycast: 'Diagnostics', portfolio: 'Portfolio', blog: 'Blog', optclicker: 'OptClicker', spaceswitcher: 'SpaceSwitcher' },
    overview: { label: 'Overview', headingHtml: 'Video enhancement built for <span class="text-editorial gradient-text">Apple silicon.</span>', body: 'VTPlayer uses native VideoToolbox, Metal, and AVFoundation APIs to upscale, interpolate, denoise, and enhance video in real time on macOS and iOS.' },
    demo: { label: 'Demo', watch: 'Watch Full Video', close: 'Close video' },
    features: { label: 'Features', headingHtml: 'Everything you need for <span class="text-editorial gradient-text">better playback.</span>', slide1num: '01 / Super Resolution', slide1title: 'Recover <span class="text-editorial gradient-text">detail</span>', slide1body: 'Hardware-aware 2x, 4x, and Quality Super Resolution modes upscale video without reducing source quality.', slide2num: '02 / Frame Interpolation', slide2title: 'Make motion feel <span class="text-editorial gradient-text">natural</span>', slide2body: 'Generate fluid in-between frames with native Apple temporal processing and PTS-aware presentation.', slide3num: '03 / Image Quality', slide3title: 'Tune every <span class="text-editorial gradient-text">frame</span>', slide3body: 'Combine denoise, motion blur, sharpness, HDR boost, and HDR colorfulness to match your display.', slide4num: '04 / Native Platforms', slide4title: 'At home on <span class="text-editorial gradient-text">Mac and iPhone</span>', slide4body: 'Native SwiftUI interfaces, responsive controls, and hardware-aware capability filtering across Apple platforms.', slide5num: '05 / Synchronization', slide5title: 'Audio and video, <span class="text-editorial gradient-text">together</span>', slide5body: 'Enhanced audio follows the rendered frame timeline while native playback keeps the system AVPlayer path.', slide5watch: 'Watch Demo', slide6num: '06 / Diagnostics', slide6title: 'Know what is <span class="text-editorial gradient-text">happening</span>', slide6body: 'Cache coverage, display rate, rendered timeline, processing time, and memory usage stay visible when you need them.', slide6btn: 'View on GitHub', slide6watch: 'Watch Demo' },
    moreFeatures: { apiLabel: 'Cache', apiBody: 'Configure the enhanced-frame memory budget without downsampling, recompressing, or discarding frames to meet it.', widgetLabel: 'Localization', widgetBody: 'VTPlayer supports English and Simplified Chinese and follows the language selected in Apple platform settings.' },
    install: { label: 'Install', headingHtml: 'Start watching in <span class="text-editorial" style="color: var(--gold-light); font-style: italic;">seconds.</span>', body: 'macOS 26.0+ and current iOS/iPadOS releases. Download the latest build from GitHub Releases.', download: 'Download', or: 'or', copy: 'Copy', disclaimer: 'VTPlayer is distributed outside the Mac App Store. If macOS blocks the app, go to System Settings → Privacy & Security and allow it to open.' },
    companions: { label: 'More apps', headingHtml: 'Explore the rest of the <span class="text-editorial gradient-text">toolkit.</span>', spaceswitcherTitle: 'SpaceSwitcher', spaceswitcherBody: 'Control which app and dock items appear in each macOS space.', optclickerTitle: 'OptClicker', optclickerBody: 'Simulate a right-click with the Option key.', learnMore: 'Learn More' },
    footer: { copyright: '© 2026 - Michael Qiu.', brand: 'VTPlayer.' },
    sidebar: { home: 'Home', overview: 'Overview', demo: 'Demo', features: 'Features', install: 'Install', companions: 'More apps', github: 'GitHub' },
    sectionLabels: { home: 'Home', overview: 'Overview', demo: 'Demo', features: 'Features', 'more-features': 'Features', install: 'Install', companions: 'More apps' }
  },
  zh: {
    site: { title: 'VTPlayer — 更清晰，更流畅' },
    hero: { heading: 'VTPlayer', tagline: '更清晰。更流畅。更出色。' },
    quicknav: { page: '页面', links: '链接', more: '更多', overview: '概览', demo: '演示', features: '功能', install: '安装', github: 'GitHub', releases: '发布', raycast: '诊断', portfolio: '主页', blog: '博客', optclicker: 'OptClicker', spaceswitcher: 'SpaceSwitcher' },
    overview: { label: '概览', headingHtml: '为<span class="text-editorial gradient-text"> Apple 芯片</span>打造的视频增强。', body: 'VTPlayer 使用原生 VideoToolbox、Metal 和 AVFoundation API，在 macOS 和 iOS 上实时提升、插帧、降噪和增强视频。' },
    demo: { label: '演示', watch: '观看完整视频', close: '关闭视频' },
    features: { label: '功能', headingHtml: '让播放体验<span class="text-editorial gradient-text">更出色。</span>', slide1num: '01 / 超分辨率', slide1title: '找回更多<span class="text-editorial gradient-text">细节</span>', slide1body: '支持硬件的 2x、4x 和高质量超分辨率，在不降低源质量的情况下提升画面。', slide2num: '02 / 帧插值', slide2title: '让运动更加<span class="text-editorial gradient-text">自然</span>', slide2body: '使用 Apple 原生时间处理生成中间帧，并按时间戳稳定呈现。', slide3num: '03 / 画质调整', slide3title: '调整每一<span class="text-editorial gradient-text">帧</span>', slide3body: '组合降噪、运动模糊、锐化、HDR 增强和鲜艳度，匹配你的显示器。', slide4num: '04 / 原生平台', slide4title: 'Mac 和 iPhone，<span class="text-editorial gradient-text">都很自然</span>', slide4body: '原生 SwiftUI 界面、响应式控制和硬件能力筛选覆盖 Apple 平台。', slide5num: '05 / 音画同步', slide5title: '让音频和视频<span class="text-editorial gradient-text">同步</span>', slide5body: '增强音频跟随已呈现的视频时间线，原生播放继续使用系统 AVPlayer。', slide5watch: '观看演示', slide6num: '06 / 诊断', slide6title: '了解正在<span class="text-editorial gradient-text">发生什么</span>', slide6body: '缓存覆盖、显示帧率、呈现时间线、处理时间和内存使用一目了然。', slide6btn: '在 GitHub 查看', slide6watch: '观看演示' },
    moreFeatures: { apiLabel: '缓存', apiBody: '配置增强帧的内存预算，不通过降采样、压缩或丢弃帧来满足限制。', widgetLabel: '本地化', widgetBody: '支持英文和简体中文，并遵循 Apple 平台设置中的语言选择。' },
    install: { label: '安装', headingHtml: '几秒钟即可<span class="text-editorial" style="color: var(--gold-light);">开始。</span>', body: '需要 macOS 26.0+ 及当前版本的 iOS/iPadOS。请从 GitHub Releases 下载最新版本。', download: '下载', or: '或', copy: '复制', disclaimer: 'VTPlayer 在 Mac App Store 之外分发。如果 macOS 阻止应用打开，请前往“系统设置 → 隐私与安全性”允许打开。' },
    companions: { label: '更多应用', headingHtml: '探索完整的<span class="text-editorial gradient-text">工具箱。</span>', spaceswitcherTitle: 'SpaceSwitcher', spaceswitcherBody: '控制每个 macOS 桌面显示哪些应用和程序坞项目。', optclickerTitle: 'OptClicker', optclickerBody: '使用 Option 键模拟右键点击。', learnMore: '了解更多' },
    footer: { copyright: '© 2026 - Michael Qiu.', brand: 'VTPlayer。' },
    sidebar: { home: '首页', overview: '概览', demo: '演示', features: '功能', install: '安装', companions: '更多应用', github: 'GitHub' },
    sectionLabels: { home: '首页', overview: '概览', demo: '演示', features: '功能', 'more-features': '功能', install: '安装', companions: '更多应用' }
  }
};
